import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CumaliAtalan
 */


public class AnaEkran extends javax.swing.JFrame {
    
    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerLoginPanel = new javax.swing.JPanel();
        kayit_ol_butonu = new javax.swing.JButton();
        dosyala_buton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parola_alani = new javax.swing.JPasswordField();
        kimlik_no_alani = new javax.swing.JTextField();
        giris_yap_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerLoginPanel.setBackground(new java.awt.Color(255, 0, 0));

        kayit_ol_butonu.setBackground(new java.awt.Color(255, 0, 0));
        kayit_ol_butonu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        kayit_ol_butonu.setForeground(new java.awt.Color(255, 255, 255));
        kayit_ol_butonu.setText("Kayıt Ol");
        kayit_ol_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayit_ol_butonuActionPerformed(evt);
            }
        });

        dosyala_buton.setBackground(new java.awt.Color(255, 0, 0));
        dosyala_buton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dosyala_buton.setForeground(new java.awt.Color(255, 255, 255));
        dosyala_buton.setText("Görüntüle");
        dosyala_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyala_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerLoginPanelLayout = new javax.swing.GroupLayout(registerLoginPanel);
        registerLoginPanel.setLayout(registerLoginPanelLayout);
        registerLoginPanelLayout.setHorizontalGroup(
            registerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLoginPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(kayit_ol_butonu)
                .addGap(45, 45, 45)
                .addComponent(dosyala_buton)
                .addGap(35, 35, 35))
        );
        registerLoginPanelLayout.setVerticalGroup(
            registerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLoginPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(registerLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kayit_ol_butonu)
                    .addComponent(dosyala_buton))
                .addGap(18, 18, 18))
        );

        loginPanel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kimlik No:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parola:");

        parola_alani.setBackground(new java.awt.Color(255, 255, 255));

        kimlik_no_alani.setBackground(new java.awt.Color(255, 255, 255));

        giris_yap_butonu.setBackground(new java.awt.Color(0, 0, 204));
        giris_yap_butonu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        giris_yap_butonu.setForeground(new java.awt.Color(255, 255, 255));
        giris_yap_butonu.setText("Giriş Yap");
        giris_yap_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_yap_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(kimlik_no_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(giris_yap_butonu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kimlik_no_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(giris_yap_butonu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerLoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayit_ol_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayit_ol_butonuActionPerformed
        
        kayitEkrani kayit_ekrani =new kayitEkrani();
        //eğer kullanıcı sisteme kayıtlı değilse kaydolmak için kayıt olma ekranına gitmesini sağlar.
        kayit_ekrani.setVisible(true);
    }//GEN-LAST:event_kayit_ol_butonuActionPerformed

    private void giris_yap_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_yap_butonuActionPerformed
        String kimlik_no = kimlik_no_alani.getText();
        String parola = new String(parola_alani.getPassword());
       
        baglanti bag =new baglanti();
        
        if(bag.login(kimlik_no, parola)){
        /*
            baglanti class'ı içinde login adında bir metod bulunur ve 
            bu metod kullanıcının veritabanına kayıtlı olup olmadığını sorgular.
        */
            JOptionPane.showMessageDialog(this, "Hoşgeldiniz "+ kimlik_no);
            oyKullanmaEkrani oyEkrani =new oyKullanmaEkrani();
            oyEkrani.setVisible(true);
        
        }else{
        
            JOptionPane.showMessageDialog(this, "Kullanıcı Bulunamadı!");
            //giriş yapamaya çalışan kullanıcı kayıtlı değilse kullanıcıyı uyarır.
        }
    }//GEN-LAST:event_giris_yap_butonuActionPerformed

    private void dosyala_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyala_butonActionPerformed
        baglanti bag =new baglanti();
        
        try {
        
            bag.kullanicilariGetir();
            /*baglanti class'ı içerisinde bulunan kullaniciGetir metodu çağırılır bu sayede masaüstünde 
            kullanicilar.txt adında bir dosya oluşturulur ve giriş yapan kullanıcıların oy tercihlerini dosyaya yazar.
            */
        } catch (IOException ex) {
        
            Logger.getLogger(AnaEkran.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        oyVerenler oyVeren =new oyVerenler();
        oyVeren.setVisible(true);
        //oyVerenler ekranını çağırarak adayların topladığı oyların gösterilmesini sağlar.
    }//GEN-LAST:event_dosyala_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dosyala_buton;
    private javax.swing.JButton giris_yap_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kayit_ol_butonu;
    private javax.swing.JTextField kimlik_no_alani;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField parola_alani;
    private javax.swing.JPanel registerLoginPanel;
    // End of variables declaration//GEN-END:variables

}
