
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CumaliAtalan
 */
class Guncelle{
    /*
    Guncelle class'ı aldığı kimlik numarası ile eşleşen bireyin oy 
    kullandığında bilgilerini veriği oy ile birlikte günceller
    */
    private String kimlik_no;
    
    public Guncelle(String kimlik_no) {
        this.kimlik_no = kimlik_no;
    }

    public String getKimlik_no(){
        return kimlik_no;
    }
    
    public void setKimlik_no(String kimlik_no) {
        this.kimlik_no = kimlik_no;
    }
    
}

public class oyKullanmaEkrani extends javax.swing.JFrame {
    
    private static ArrayList<Guncelle> guncel_list =new ArrayList<Guncelle>();
    
    public static ArrayList<Guncelle> getguncel_list() {
        return  guncel_list;
    }
    
    public static void setGuncel_list(ArrayList<Guncelle> guncel_list) {
        oyKullanmaEkrani.guncel_list = guncel_list;
    }
    
    /**
     * Creates new form oyKullanmaEkrani
     */
    public oyKullanmaEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        aday1_radiobutton = new javax.swing.JRadioButton();
        aday2_radiobutton = new javax.swing.JRadioButton();
        aday3_radiobutton = new javax.swing.JRadioButton();
        aday4_radiobutton = new javax.swing.JRadioButton();
        oy_kullan_buton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        aday1_radiobutton.setBackground(new java.awt.Color(0, 0, 204));
        aday1_radiobutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday1_radiobutton.setForeground(new java.awt.Color(255, 255, 255));
        aday1_radiobutton.setText("Aday 1");
        aday1_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aday1_radiobuttonActionPerformed(evt);
            }
        });

        aday2_radiobutton.setBackground(new java.awt.Color(0, 0, 204));
        aday2_radiobutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday2_radiobutton.setForeground(new java.awt.Color(255, 255, 255));
        aday2_radiobutton.setText("Aday 2");
        aday2_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aday2_radiobuttonActionPerformed(evt);
            }
        });

        aday3_radiobutton.setBackground(new java.awt.Color(0, 0, 204));
        aday3_radiobutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday3_radiobutton.setForeground(new java.awt.Color(255, 255, 255));
        aday3_radiobutton.setText("Aday 3");
        aday3_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aday3_radiobuttonActionPerformed(evt);
            }
        });

        aday4_radiobutton.setBackground(new java.awt.Color(0, 0, 204));
        aday4_radiobutton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday4_radiobutton.setForeground(new java.awt.Color(255, 255, 255));
        aday4_radiobutton.setText("Aday 4");
        aday4_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aday4_radiobuttonActionPerformed(evt);
            }
        });

        oy_kullan_buton.setBackground(new java.awt.Color(255, 0, 0));
        oy_kullan_buton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        oy_kullan_buton.setForeground(new java.awt.Color(255, 255, 255));
        oy_kullan_buton.setText("Oy Kullan");
        oy_kullan_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oy_kullan_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oy_kullan_buton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aday1_radiobutton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(aday2_radiobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aday3_radiobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aday4_radiobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(aday1_radiobutton)
                .addGap(18, 18, 18)
                .addComponent(aday2_radiobutton)
                .addGap(18, 18, 18)
                .addComponent(aday3_radiobutton)
                .addGap(18, 18, 18)
                .addComponent(aday4_radiobutton)
                .addGap(18, 18, 18)
                .addComponent(oy_kullan_buton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aday1_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aday1_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aday1_radiobuttonActionPerformed

    private void aday2_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aday2_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aday2_radiobuttonActionPerformed

    private void aday3_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aday3_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aday3_radiobuttonActionPerformed

    private void aday4_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aday4_radiobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aday4_radiobuttonActionPerformed

    private void oy_kullan_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oy_kullan_butonActionPerformed
        oylamaDosyaİşlemi oyDosyaİşlemi =new oylamaDosyaİşlemi();
        baglanti bag =new baglanti();
        
        
        if(aday1_radiobutton.isSelected()){
           //aday1_radiobutton seçilmesi halinde 1. aday lehine oylama yapılmış olur.
           
            for(Guncelle guncelle : guncel_list){
                //Guncelle class'ından oluşturulan guncel_list ile gelen kişinin oyunu aday 1'e veridği güncellenir.
                
               bag.oyGuncelle(guncelle.getKimlik_no(), "Aday 1");
               // bag içerisindeki oyGuncelle metodu sayesinde kullanıcıyı günceller
               JOptionPane.showMessageDialog(this, "İşlem Başarılı!!\nAday 1 lehine oy kullanıldı...");
               break;
           }
        }

        if(aday2_radiobutton.isSelected()){

            for(Guncelle guncelle : guncel_list){
            
                bag.oyGuncelle(guncelle.getKimlik_no(), "Aday 2");
                JOptionPane.showMessageDialog(this, "İşlem Başarılı!!\nAday 2 lehine oy kullanıldı...");
                break;
           }
        }

        if(aday3_radiobutton.isSelected()){

            for(Guncelle guncelle : guncel_list){
            
                bag.oyGuncelle(guncelle.getKimlik_no(), "Aday 3");
                JOptionPane.showMessageDialog(this, "İşlem Başarılı!!\nAday 3 lehine oy kullanıldı...");
                break;
           }
        }

        if(aday4_radiobutton.isSelected()){
           
            for(Guncelle guncelle : guncel_list){
            
                bag.oyGuncelle(guncelle.getKimlik_no(), "Aday 4");
                JOptionPane.showMessageDialog(this, "İşlem Başarılı!!\nAday 4 lehine oy kullanıldı...");
                break;
           }
        }
        
        setVisible(false);
    }//GEN-LAST:event_oy_kullan_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyKullanmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyKullanmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyKullanmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyKullanmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyKullanmaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aday1_radiobutton;
    private javax.swing.JRadioButton aday2_radiobutton;
    private javax.swing.JRadioButton aday3_radiobutton;
    private javax.swing.JRadioButton aday4_radiobutton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton oy_kullan_buton;
    // End of variables declaration//GEN-END:variables
}
