
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author CumaliAtalan
 */
public class oyVerenler extends javax.swing.JFrame {

    /**
     * Creates new form oyVerenler
     */
    public oyVerenler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        aday1 = new javax.swing.JLabel();
        aday2 = new javax.swing.JLabel();
        aday3 = new javax.swing.JLabel();
        aday4 = new javax.swing.JLabel();
        aday1_sonuc = new javax.swing.JLabel();
        aday2_sonuc = new javax.swing.JLabel();
        aday3_sonuc = new javax.swing.JLabel();
        aday4_sonuc = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        aday1.setBackground(new java.awt.Color(255, 255, 255));
        aday1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday1.setForeground(new java.awt.Color(255, 255, 255));
        aday1.setText("Aday 1:");
        aday1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aday1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        aday2.setBackground(new java.awt.Color(255, 255, 255));
        aday2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday2.setForeground(new java.awt.Color(255, 255, 255));
        aday2.setText("Aday 2:");

        aday3.setBackground(new java.awt.Color(255, 255, 255));
        aday3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday3.setForeground(new java.awt.Color(255, 255, 255));
        aday3.setText("Aday 3:");

        aday4.setBackground(new java.awt.Color(255, 255, 255));
        aday4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday4.setForeground(new java.awt.Color(255, 255, 255));
        aday4.setText("Aday 4:");

        aday1_sonuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday1_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        aday1_sonuc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aday1_sonucAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        aday2_sonuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday2_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        aday2_sonuc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aday2_sonucAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        aday3_sonuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday3_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        aday3_sonuc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aday3_sonucAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        aday4_sonuc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        aday4_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        aday4_sonuc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                aday4_sonucAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aday2)
                    .addComponent(aday1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aday1_sonuc, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(aday2_sonuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(aday3)
                        .addGap(18, 18, 18)
                        .addComponent(aday3_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(aday4)
                        .addGap(18, 18, 18)
                        .addComponent(aday4_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aday1)
                    .addComponent(aday3)
                    .addComponent(aday1_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aday3_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aday2)
                    .addComponent(aday4)
                    .addComponent(aday2_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aday4_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aday1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aday1AncestorAdded

    }//GEN-LAST:event_aday1AncestorAdded

    private void aday1_sonucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aday1_sonucAncestorAdded
        baglanti bag = new baglanti();
        //baglanti class'ından bag adında bir tane ogje oluşturulur.
        
        String sonuc1 = String.valueOf(bag.sayım1());
        /*
        aday 1'in topladığı oylar bag içerisinde bulunan sayim1 metodu sayesinde 
        hesaplanır. Gelen veri string olarak pars edilir.
        
        */
        aday1_sonuc.setText(sonuc1);
        //aday1_sonuc etiketini sonuc1 içerisindeki veri ile değiştirir.
    }//GEN-LAST:event_aday1_sonucAncestorAdded

    private void aday2_sonucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aday2_sonucAncestorAdded
        baglanti bag = new baglanti();
        String sonuc2 = String.valueOf(bag.sayım2());
        aday2_sonuc.setText(sonuc2);
    }//GEN-LAST:event_aday2_sonucAncestorAdded

    private void aday3_sonucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aday3_sonucAncestorAdded
        baglanti bag = new baglanti();
        String sonuc3 = String.valueOf(bag.sayım3());
        aday3_sonuc.setText(sonuc3);
    }//GEN-LAST:event_aday3_sonucAncestorAdded

    private void aday4_sonucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_aday4_sonucAncestorAdded
        baglanti bag = new baglanti();
        String sonuc4 = String.valueOf(bag.sayım4());
        aday4_sonuc.setText(sonuc4);
    }//GEN-LAST:event_aday4_sonucAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oyVerenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oyVerenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oyVerenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oyVerenler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oyVerenler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aday1;
    private javax.swing.JLabel aday1_sonuc;
    private javax.swing.JLabel aday2;
    private javax.swing.JLabel aday2_sonuc;
    private javax.swing.JLabel aday3;
    private javax.swing.JLabel aday3_sonuc;
    private javax.swing.JLabel aday4;
    private javax.swing.JLabel aday4_sonuc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
